# Use the official Elasticsearch image as the base image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.0

# Copy your custom elasticsearch.yml configuration file
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml